hemi = {'lh' 'rh'};
str = 'VOT';
cam = {[40 -5 0] [180-40 -5 0]};
subj = 'S027';

for p=1:length(hemi)
  dir0 = sprintf('/software/freesurfer/subjects/%s/',subj);
  file0 = sprintf('%s/surf/rois/%s.%s.mgz',dir0,hemi{p},str);
  cmd = sprintf(['freeview -f /software/freesurfer/subjects/%s/surf/%s.inflated' ...
                 ':overlay=%s' ...
                 ':edgethickness=0 -cam Zoom 1.2 Azimuth %d Elevation %d Roll %d -viewsize 900 900'], ...
           subj, ...
           hemi{p}, ...
           file0, ...
           cam{p}(1),cam{p}(2),cam{p}(3));
  unix(cmd);
end
