function V = volumedecompress(volstruct)
%V = volumedecompress(volstruct)
%
%decompress a volstruct generated by volumecompress

if(~isstruct(volstruct))
    V=volstruct;
    return;
end

if(isnumeric(volstruct.maskval))
    V=zeros(volstruct.volsize,'like',volstruct.maskval);
elseif(islogical(volstruct.maskval))
    V=false(volstruct.volsize);
end
V(volstruct.maskidx)=volstruct.maskval;
